add emotes for players
aresrpg/resourcepacks pull request #7
Opened 2022-12-06 22:33 UTC by SohKey

2022-12-08 17:26 UTC, Sceat reviewed
Is the `memes` subfolder necessary ?

2022-12-12 20:27 UTC, SohKey commented
> Is the `memes` subfolder necessary ?

Yep, i will soon push a new version of the pack were there is multiple other folders in the texture one

2022-12-18 12:34 UTC, Sceat commented
Please provide an explanation for the `memes` subfolder, and keep in mind this is the demo pack, aresrpg will only use https://github.com/aresrpg/resourcepacks-closed

2022-12-27 14:35 UTC, Sceat commented
WHERE IS THE FUCKING DAMN EXPLANATION FOR THE `memes` SUBFOLDER BLYAT

2022-12-29 13:29 UTC, SohKey commented
> 
lel the fucking damn explanation for the `memes` subfolder is on your DAMNN search engine juste type "what is a meme" :)

More seriously what there is to explain ? And where should i put it ?
![image](https://user-images.githubusercontent.com/45180021/209960122-ece4de9a-ef2b-43a2-8c25-fa459e9cba49.png)

2022-12-29 15:18 UTC, Sceat commented
![image](https://user-images.githubusercontent.com/11330271/209973441-9b4afaeb-ce83-4a40-b30b-a5131e8bfea9.png)

2022-12-29 15:18 UTC, Sceat commented
<img width="323" alt="image" src="https://user-images.githubusercontent.com/11330271/209973272-e551a2bd-fc9d-4daf-984e-7057e5f81cb9.png">

I know what a meme is blyat, there is no usecase for this subfolder so if u have no explanations follow the flat structure and do `textures/emotes/` only

2022-12-29 16:52 UTC, DeltaEvo requested changes

2022-12-29 16:52 UTC, DeltaEvo commented on assets/minecraft/lang/en_us.json
> +  "sign.edit": "§eMontant de kAres: ",
This seems unrelated to this PR

2022-12-29 16:52 UTC, DeltaEvo commented on assets/minecraft/lang/en_us.json
> +  "aresrpg.emotes.pepe": 3,
```suggestion
  "aresrpg.emotes.ban": "1",
  "aresrpg.emotes.sheesh": "2",
  "aresrpg.emotes.pepe": "3",
```

2023-01-02 21:10 UTC, DeltaEvo approved these changes

2023-01-02 21:11 UTC, merged